exports.actionList = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    RESET_PASSWORD: 'RESET_PASSWORD', //x

    CREATE_USER: 'CREATE_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',

    CREATE_DEVICE: 'CREATE_DEVICE',
    UPDATE_DEVICE: 'UPDATE_DEVICE',
    DELETE_DEVICE: 'DELETE_DEVICE',

    CREATE_DEVICE_BOOKING: 'CREATE_DEVICE_BOOKING',
    UPDATE_DEVICE_BOOKING: 'UPDATE_DEVICE_BOOKING',
    PROCESS_EDIT_REQUEST: 'PROCESS_EDIT_REQUEST',
};
