exports.actionList = {
    CREATE_USER: 'CREATE_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
    RESET_PASSWORD: 'RESET_PASSWORD',
    GET_USER_LIST: 'GET_USER_LIST',
    GET_USER_BY_ID: 'GET_USER_BY_ID',

    
};
